version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/var/www/myapp
    ports:
      - "80:3000"
    env_file:
      - env
